"""ORM models. Importing this package registers every table on ``Base.metadata``."""

from app.database.models.identity import Membership, Organization, OrgRole, RefreshToken, User
from app.database.models.platform import (
    AgentRecord,
    AuditLog,
    Evaluation,
    EvaluationResult,
    Memory,
    ModelRecord,
    ModelUsage,
    Plan,
    Subscription,
    UsageRecord,
)
from app.database.models.projects import (
    DbConnection,
    Document,
    DocumentChunk,
    FileDependency,
    IndexJob,
    Project,
    ProjectFile,
    ProjectStatus,
    Symbol,
)
from app.database.models.runs import (
    TERMINAL_STATUSES,
    Approval,
    ApprovalStatus,
    ChangeSet,
    ChangeSetFile,
    Conversation,
    Message,
    RunEvent,
    RunStep,
    Task,
    TaskRun,
    TaskStatus,
    ToolRun,
)

__all__ = [
    "TERMINAL_STATUSES",
    "AgentRecord",
    "Approval",
    "ApprovalStatus",
    "AuditLog",
    "ChangeSet",
    "ChangeSetFile",
    "Conversation",
    "DbConnection",
    "Document",
    "DocumentChunk",
    "Evaluation",
    "EvaluationResult",
    "FileDependency",
    "IndexJob",
    "Membership",
    "Memory",
    "Message",
    "ModelRecord",
    "ModelUsage",
    "OrgRole",
    "Organization",
    "Plan",
    "Project",
    "ProjectFile",
    "ProjectStatus",
    "RefreshToken",
    "RunEvent",
    "RunStep",
    "Subscription",
    "Symbol",
    "Task",
    "TaskRun",
    "TaskStatus",
    "ToolRun",
    "UsageRecord",
    "User",
]
